alias: Restore Seasonal Mode After Work
trigger:
  - platform: time
    at: "17:00:00"
condition: []
action:
  - service: input_select.select_option
    data:
      option: >
        {% set month = now().month %}
        {% if month in [4,5,6,7,8,9] %}
          Summer
        {% else %}
          Winter
        {% endif %}
    target:
      entity_id: input_select.seasonal_mode
mode: single