blueprint:
  name: Weather-Based Thermostat with Day/Night and Seasonal Mode
  description: Adjust thermostat based on outdoor temperature, time of day, and season
  domain: automation
  input:
    weather_entity:
      name: Weather Entity
      selector:
        entity:
          domain: weather
    thermostat_entity:
      name: Thermostat Entity
      selector:
        entity:
          domain: climate
    seasonal_mode:
      name: Seasonal Mode Selector
      selector:
        entity:
          domain: input_select

trigger:
  - platform: time_pattern
    minutes: "/30"

condition: []

action:
  - choose:
      - conditions:
          - condition: state
            entity_id: !input seasonal_mode
            state: "Winter"
        sequence:
          - choose:
              - conditions:
                  - condition: time
                    after: "22:00:00"
                    before: "08:00:00"
                sequence:
                  - choose:
                      - conditions:
                          - condition: numeric_state
                            entity_id: !input weather_entity
                            attribute: temperature
                            below: 50
                        sequence:
                          - service: climate.set_temperature
                            target:
                              entity_id: !input thermostat_entity
                            data:
                              temperature: 70
                      - conditions:
                          - condition: numeric_state
                            entity_id: !input weather_entity
                            attribute: temperature
                            above: 50
                            below: 70
                        sequence:
                          - service: climate.set_temperature
                            target:
                              entity_id: !input thermostat_entity
                            data:
                              temperature: 68
                      - conditions:
                          - condition: numeric_state
                            entity_id: !input weather_entity
                            attribute: temperature
                            above: 70
                        sequence:
                          - service: climate.set_temperature
                            target:
                              entity_id: !input thermostat_entity
                            data:
                              temperature: 66
          - conditions:
              - condition: time
                after: "08:00:00"
                before: "22:00:00"
            sequence:
              - choose:
                  - conditions:
                      - condition: numeric_state
                        entity_id: !input weather_entity
                        attribute: temperature
                        below: 50
                    sequence:
                      - service: climate.set_temperature
                        target:
                          entity_id: !input thermostat_entity
                        data:
                          temperature: 72
                  - conditions:
                      - condition: numeric_state
                        entity_id: !input weather_entity
                        attribute: temperature
                        above: 50
                        below: 70
                    sequence:
                      - service: climate.set_temperature
                        target:
                          entity_id: !input thermostat_entity
                        data:
                          temperature: 70
                  - conditions:
                      - condition: numeric_state
                        entity_id: !input weather_entity
                        attribute: temperature
                        above: 70
                        below: 80
                    sequence:
                      - service: climate.set_temperature
                        target:
                          entity_id: !input thermostat_entity
                        data:
                          temperature: 68
                  - conditions:
                      - condition: numeric_state
                        entity_id: !input weather_entity
                        attribute: temperature
                        above: 80
                    sequence:
                      - service: climate.set_temperature
                        target:
                          entity_id: !input thermostat_entity
                        data:
                          temperature: 66

      - conditions:
          - condition: state
            entity_id: !input seasonal_mode
            state: "Summer"
        sequence:
          - choose:
              - conditions:
                  - condition: time
                    after: "22:00:00"
                    before: "08:00:00"
                sequence:
                  - choose:
                      - conditions:
                          - condition: numeric_state
                            entity_id: !input weather_entity
                            attribute: temperature
                            below: 50
                        sequence:
                          - service: climate.set_temperature
                            target:
                              entity_id: !input thermostat_entity
                            data:
                              temperature: 66
                      - conditions:
                          - condition: numeric_state
                            entity_id: !input weather_entity
                            attribute: temperature
                            above: 50
                            below: 70
                        sequence:
                          - service: climate.set_temperature
                            target:
                              entity_id: !input thermostat_entity
                            data:
                              temperature: 66
                      - conditions:
                          - condition: numeric_state
                            entity_id: !input weather_entity
                            attribute: temperature
                            above: 70
                            below: 80
                        sequence:
                          - service: climate.set_temperature
                            target:
                              entity_id: !input thermostat_entity
                            data:
                              temperature: 68
                      - conditions:
                          - condition: numeric_state
                            entity_id: !input weather_entity
                            attribute: temperature
                            above: 80
                        sequence:
                          - service: climate.set_temperature
                            target:
                              entity_id: !input thermostat_entity
                            data:
                              temperature: 70
          - conditions:
              - condition: time
                after: "08:00:00"
                before: "22:00:00"
            sequence:
              - choose:
                  - conditions:
                      - condition: numeric_state
                        entity_id: !input weather_entity
                        attribute: temperature
                        below: 50
                    sequence:
                      - service: climate.set_temperature
                        target:
                          entity_id: !input thermostat_entity
                        data:
                          temperature: 70
                  - conditions:
                      - condition: numeric_state
                        entity_id: !input weather_entity
                        attribute: temperature
                        above: 50
                        below: 70
                    sequence:
                      - service: climate.set_temperature
                        target:
                          entity_id: !input thermostat_entity
                        data:
                          temperature: 70
                  - conditions:
                      - condition: numeric_state
                        entity_id: !input weather_entity
                        attribute: temperature
                        above: 70
                        below: 80
                    sequence:
                      - service: climate.set_temperature
                        target:
                          entity_id: !input thermostat_entity
                        data:
                          temperature: 72
                  - conditions:
                      - condition: numeric_state
                        entity_id: !input weather_entity
                        attribute: temperature
                        above: 80
                    sequence:
                      - service: climate.set_temperature
                        target:
                          entity_id: !input thermostat_entity
                        data:
                          temperature: 74
mode: single